<script setup lang="ts">
import { Card, CardContent } from "@/components/ui/card";
import PublicPageLayout from "./PublicPageLayout.vue";
</script>

<template>
	<PublicPageLayout>
		<div class="mx-auto max-w-3xl flex flex-col gap-2">
			<span class="px-1 text-xs sm:text-sm font-bold uppercase tracking-widest text-primary">Legal</span>
			<span class="font-heading text-4xl font-extrabold tracking-tight sm:text-5xl">Privacy Policy</span>
			<div class="flex gap-1">
				<span class="text-sm font-bold">Last Updated:</span>
				<span class="text-sm text-muted-foreground">11 August 2026</span>
			</div>

			<span class="py-4 text-lg leading-relaxed text-muted-foreground">
				Setil is an open-source application designed for cost splitting developed by Joel Cutler. This Privacy Policy
				outlines how your information is handled when you use the app, why it is needed, and the choices available to
				you.
			</span>

			<Card>
				<CardContent class="prose-setil p-6 sm:p-8">
					<section>
						<h2>1. Information We Collect</h2>
						<p>When you use Setil, we process the following minimum data required for app functionality:</p>
						<ul>
							<li>
								<strong>Account information:</strong> When you sign in with your Google Account, we receive your basic
								authentication details (such as your email address, display name, and profile picture URL) provided by
								Google Firebase Authentication.
							</li>
							<li>
								<strong>Photos and Images:</strong> If you choose to upload a custom profile picture or group avatar,
								the image file is uploaded and hosted via Cloudinary.
							</li>
							<li>
								<strong>User-Generated Data:</strong> Expense details, groups, balances, and cost-splitting transactions
								you create within the app are stored in our Firebase Database (Firestore). Payment details are encrypted
								before storage.
							</li>
							<li>
								<strong>Device Identifiers & Push Tokens:</strong> If you enable push notifications, we collect unique
								Firebase Cloud Messaging (FCM) tokens, and FIrebase Installation IDs (FIDs) generated by your device to
								send real-time notification alerts regarding group activity and balance updates.
							</li>
						</ul>
					</section>
					<section>
						<h2>2. How Your Data Is Used</h2>
						<ul>
							<li>To authenticate your identity and provide your Setil account.</li>
							<li>To synchronise groups, expenses, and balances between group members and devices.</li>
							<li>To store and display avatars and, when enabled, deliver notifications.</li>
							<li>We <strong>do not</strong> track your activity, run advertisements, or profile you for marketing.</li>
							<li>
								We <strong>do not</strong> sell, trade, or rent your personal information or user-generated data to
								third parties.
							</li>
						</ul>
					</section>
					<section>
						<h2>3. Third-Party Services</h2>
						<p>The app relies on the following third-party infrastructure service providers to function:</p>
						<ul>
							<li>
								<strong>Firebase / Google Cloud:</strong> Handles user authentication, secure cloud database storage
								(Firestore), and push notification delivery (Firebase Cloud Messaging). Please review
								<a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
									Google's Privacy Policy
								</a>
								for details on their security practices.
							</li>
							<li>
								<strong>Cloudinary:</strong> Acts as a content delivery network and cloud media host for user-uploaded
								profile and avatar images. Please review
								<a href="https://cloudinary.com/privacy" target="_blank" rel="noopener noreferrer">
									Cloudinary's Privacy Policy
								</a>
								for more information.
							</li>
							<li>
								<strong>Vercel:</strong> Used for web hosting and server-side API functions. See
								<a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">
									Vercel's Privacy Policy
								</a>
								for more details.
							</li>
						</ul>
					</section>
					<section>
						<h2>4. Open Source Transparency</h2>
						<p>
							Setil is open-source. You can inspect the source code and verify our data handling practices on GitHub at:
							<a href="https://github.com/jcbyte/setil" target="_blank" rel="noopener noreferrer">
								github.com/jcbyte/setil
							</a>
						</p>
					</section>
					<section>
						<h2>5. Data Deletion</h2>
						<p>You have the right to request the deletion of your account and personal information at any time.</p>
						<ul>
							<li>
								<strong>Personal Data Erased:</strong> Your authentication credentials, name, profile pictures (hosted
								on Cloudinary), push notification tokens, and direct account settings will be permanently deleted from
								our servers.
							</li>
							<li>
								<strong>Shared Ledger Data:</strong> To maintain financial and balance integrity for remaining group
								members, historical transaction entries created by you will be anonymised (disassociated from your
								identity) rather than deleted.
							</li>
							<li>
								<strong>How to Request:</strong> To request account deletion, contact Joel Cutler directly via email at
								<a href="mailto:joelcutler108@gmail.com?subject=Setil">joelcutler108@gmail.com</a>.
							</li>
						</ul>
					</section>
					<section>
						<h2>6. Changes to this policy</h2>
						<p>
							This page may be updated when Setil's features or data practices change. The date above identifies the
							latest version.
						</p>
					</section>
					<section>
						<h2>7. Contact</h2>
						<p>
							For questions or concerns regarding this policy, contact Joel Cutler (the developer) via email at
							<a href="mailto:joelcutler108@gmail.com?subject=Setil">joelcutler108@gmail.com</a>.
						</p>
					</section>
				</CardContent></Card
			>
		</div>
	</PublicPageLayout>
</template>

<style scoped>
.prose-setil section + section {
	margin-top: 2rem;
}

.prose-setil h2 {
	margin-bottom: 0.75rem;
	font-family: var(--font-heading);
	font-size: 1.25rem;
	font-weight: 700;
	letter-spacing: -0.025em;
}

.prose-setil p,
.prose-setil li {
	color: var(--muted-foreground);
	line-height: 1.7;
}

.prose-setil p + p {
	margin-top: 0.75rem;
}

.prose-setil ul {
	margin-top: 0.75rem;
	list-style: disc;
	padding-left: 1.25rem;
}

.prose-setil li + li {
	margin-top: 0.6rem;
}

.prose-setil strong {
	color: var(--foreground);
	font-weight: 600;
}

.prose-setil a {
	color: var(--foreground);
	font-weight: 500;
	text-decoration: underline;
	text-underline-offset: 4px;
}

.prose-setil a:hover {
	color: var(--primary);
}
</style>
