# Generated by Django 4.2.2 on 2023-07-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groups_transactions_user_name_transactionsfor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupUsers',
            new_name='GroupUser',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='TransactionsFor',
            new_name='TransactionFor',
        ),
    ]
