# Generated by Django 4.2.2 on 2023-07-01 17:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_groups_group_rename_groupusers_groupuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.TextField(default=api.models.genUniqueCode, max_length=42, unique=True),
        ),
    ]
