# Generated by Django 4.2.2 on 2023-07-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
            preserve_default=False,
        ),
    ]
